= Advanced content
:toc: right
:imagesdir: media

We've seen basic content types, now let's explore some of the more advanced aspects. We'll look at item sets and option sets and how they can help us both structure our data and make our input forms clearer and easier to use.


== Mixins

We can use mixins to reuse input field sets across different content types!

=== Task

Create another content type that reuses a lot of the fields from our preexisting one. Solve it by using a Mixin.

=== Next / after mixins

// We might want to move this to the next section? Making it about input reuse and grouping / advanced content.

Mixins provide a handy way of reusing the same inputs across different content types. However, if you want to group a set of fields as a logical unit, you may be better off looking at item sets. Luckily, that's coming right up.


[TIP]
====
For @the: Item sets are basic hierarchical data structures (think JSON, Rust's `struct`, etc.).

Option sets are sort of like union types / enums: if they are single-select option sets, then they're like union types. However, this is just a specialized version of the multi-select option sets. If they are multi-select option types, then it's just a set where you can pick which options to include and exclude (giving us the standard 2^n^ number of possibilities 🤓).
====

== Item sets

Item sets provide a convenient way to abstract away certain details.

Item sets allow you to group a number of inputs together as a logical unit ...

You can also nest item sets, ...

When using item sets, ...

== Option sets

Enonic XP also sports something called option sets. They are visually similar to item sets when viewed in Content Studio, but are a different way of grouping items together.

Explain how multi-sets work.

NOTE: Can you use item sets within option sets? I need to try out option sets to properly understand what they're about.

== Task

Let's add use both item sets and option sets!
