= Get to know the basics of Enonic development
:toc: right
:imagesdir: media
:experimental:
:document: chapter

In this {document} we'll introduce the fundamental concepts of Enonic XP development. You'll get a brief introduction to the Enonic command line interface (CLI), XP _sandboxes_, starter kits, and building and deploying apps on XP. By the end of the {document} you'll have spun up an instance of XP and deployed an app to it.

There's lots to cover, so let's get to it, shall we?

== The Enonic CLI

NOTE: If you haven't installed the Enonic CLI yet, be sure to check out the xref:setup#_installing_the_enonic_cli[installation instructions in the previous {document}].

The Enonic command line interface is a powerful tool, built specifically for the Enonic platform. The CLI allows you to interact with XP instances and deploy and develop apps.

To see all available options, run the following command in your terminal:

    enonic

It should output something that looks a bit like this:

.Main help page
----
Enonic CLI v.1.5.1
Manage XP instances, home folders and projects

USAGE:
   enonic [global options] command [command options] [arguments...]

COMMANDS:
     snapshot  Create and restore snapshots
     dump      Dump and load complete repositories
     export    Export data from a given repository, branch and content path.
     import    Import data from a named export.
     app       Install, stop and start applications
     repo      Tune and manage repositories
     cms       CMS commands
     system    System commands
     latest    Check for latest version
     vacuum    Removes old version history and segments from content storage
     help, h   Shows a list of commands or help for one command

PROJECT COMMANDS:
     sandbox  Manage XP development instances
     project  Manage XP development projects

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
----

If you want to know more about how to use one of the subcommands, you can use the `help` subcommand. For instance, if you want to know more about the `sandbox` subcommand, you can run

    enonic sandbox help

This should result in something like the following being printed to your screen:

.Sandbox help page
----
NAME:
   Enonic CLI sandbox - Manage XP development instances

USAGE:
   Enonic CLI sandbox [global options] command [command options] [arguments...]

VERSION:
   1.5.1

COMMANDS:
     list, ls         List all sandboxes
     start            Start the sandbox.
     stop             Stop the sandbox started in detached mode.
     create           Create a new sandbox.
     delete, del, rm  Delete a sandbox
     upgrade, up      Upgrades the distribution version.

GLOBAL OPTIONS:
   --help, -h  show help
----


== Sandboxes

An essential part of Enonic app development is to have an instance of Enonic XP running locally. These instances are also known as "Sandboxes".

To create a new sandbox, we will use the CLI. Execute the following command:

    enonic sandbox create

When prompted, give your sandbox the name: `tutorial`. Next choose to use the latest version of XP (from the top of the list.)

The CLI will now download the Enonic XP SDK distribution for your operating system, and link it to the sandbox.

.Creating sandbox
----
? Sandbox name: tutorial
? Enonic XP distribution: mac-sdk-7.2.0
Downloading distro [===================>--------------------------------]  37.64%
----

Once completed, we may start the sandbox using the CLI:

    enonic sandbox start

Choose the `tutorial` sandbox, and you will see it booting up in your terminal

.Output when booting sandbox
----
                         _____
____________________________(_)______   ____  _________
_  _ \_  __ \  __ \_  __ \_  /_  ___/   __  |/_/__  __ \
/  __/  / / / /_/ /  / / /  / / /__     __>  < __  /_/ /
\___//_/ /_/\____//_/ /_//_/  \___/     /_/|_| _  .___/
                                               /_/

# Enonic XP 7.2.0
# Built on 2019-12-19T15:18:13Z (hash = 39d4b215fd2009d7ba65e07efc54ebad50638741, branch = master)
# OpenJDK 64-Bit Server VM 11.0.5 (AdoptOpenJDK)
# Mac OS X 10.15.1 (x86_64)
# Install directory is /Users/tsi/.enonic/distributions/enonic-xp-mac-sdk-7.2.0
# Home directory is /Users/tsi/.enonic/sandboxes/tutorial/home
[...]
----


The initial output is telling you a lot of information about this sandbox, including the "Home" directory of your sandbox. This may come in handy at a later point in time.

After sandbox has started, you should see the following output in your terminal:

----
[...] - Started xp@523d2774{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[...] - Started api@22bce39c{HTTP/1.1,[http/1.1]}{0.0.0.0:4848}
[...] - Started status@37f8a3e8{HTTP/1.1,[http/1.1]}{0.0.0.0:2609}
[...] - Started @12314ms
[...] - Started Jetty
[...] - Listening on ports [8080](xp), [4848](management) and [2609](monitoring)
[...] - Searching for installed applications
[...] - Found [0] installed applications
[...] - Started Enonic XP in 11207 ms
----

This indicates that your local XP instance is now serving on the following ports:
 
* *8080* Web
* *4848* Management API (Used by CLI when running commands against an XP instance)
* *2609* Monitoring API (Use for metrics and instance info)

INFO: To stop your sandbox, simply press btn:ctrl-c in the running terminal, or `enonic sandbox stop` in a new terminal.


NOTE: If you have problems booting the sandbox, it may be that one or more of the ports used by XP are already in use. Check the log to see if something went wrong.


== Admin console

With your sandbox running, lets have a look at XP's admin console.
Point your browser to http://localhost:8080.

You should now see the default XP login screen:

TODO: "login screen"


From the login screen, simply click "sign in without a user" (You may always create an administrator user later).

After signing in, you will be greeted by the "Welcome tour". Complete the tour, and install the applications listed in the final step. Some of these apps will come in handy later in this tutorial.

TODO: Screenshots of welcome tour

NOTE: If the welcome tour does not start automatically, simply click the "Welcome tour" icon on the home screen to launch it manually.

== Projects and starters

You are now set to create your first XP project. 

Luckily you will not have to start from scratch. We have provide a range of different project templates (AKA starters)  that you will be using throughout this tutorial.

The complete list of starters can be found on https://market.enonic.com/starters[Enonic Market]

Use the CLI to create your first app.

. Launch a new terminal
. From a suitable directory for projects files, run the following command:

    enonic project create

. Choose `Vanilla starter` from the list of available starters
+
NOTE: The vanilla starter is a minimalistic project template, containing only the essential files required for an XP app
+
. Go with the default name: `com.example.myproject`
+
NOTE: The project names are important, since XP does not support two apps with the same name running within an instance.
+
. Go with default values for destination folder and version.
. Next, link the project to the  `tutorial` sandbox we created earlier.
. Finally, skip opening the starter documentation

A new folder `myproject/` was created during the process.
The contents of this folder now contain the essentials for an XP application:

.Essential XP project structure
[source,files]
----
gradle.properties <--1-->
build.gradle <--2-->
src/
  main/
    resources/ <!--3-->
    java/ <!--4-->
----

<1> Contains the standard project settings, as defined by the CLI
<2> Main build file for defining dependencies and more 
<3> Main project folder - JavaScript code and assets are placed here
<4> Optional folder for Java (XP apps may also contain Java)


== Building and deploying

With a brand new project setup, we are ready to build (compile) it for the first time, using the terminal once more:

. Change to the project directory:

    cd myproject

. Start the build with Enonic CLI:

    enonic project build

.Sample output from build process
----
Building in sandbox 'tutorial'...
Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 5s
3 actionable tasks: 3 executed
----


After building, a new file (and some folders) was created in your project structure: `build/libs/myproject.jar`. This is the actual application executable file.

To deploy the app to the sandbox, use the CLI once again: 

. From the project folder:

    enonic project deploy

The application file will now be copied your sandbox' home/deploy/ folder. XP then detects and starts the app.

Confirm that your application was started by looking at the log file from the sandbox' terminal window:

.Application output
----
[...] - Local application [com.example.myproject] installed successfully
[...] - Application [com.example.myproject] started successfully
----

NOTE: Running `enonic project deploy` will also build your project if needed. It will even start the sandbox if it is not running already.

You can also verify that the application was installed by using the admin console. Open the "Applications" app from the main launcher panel to find the application in the list.

TODO Screenshot:

Congratulations on building your first Enonic application :-)


== Summary

=== Useful links

=== Next