= Get to know the basics of Enonic development
:toc: right
:imagesdir: media
:experimental:
:document: chapter

In this {document} we'll introduce the fundamental concepts of Enonic XP development. You'll get a brief introduction to the Enonic command line interface (CLI), XP _sandboxes_, starter kits, and building and deploying apps on XP. By the end of the {document} you'll have spun up an instance of XP and deployed an app to it.

There's lots to cover, so let's get to it, shall we?

== The Enonic CLI

NOTE: If you haven't installed the Enonic CLI yet, be sure to check out the xref:setup#_installing_the_enonic_cli[installation instructions in the previous {document}].

The Enonic command line interface is a powerful tool, built specifically for the Enonic platform. The CLI allows you to interact with XP instances and deploy and develop apps.

To see all available options, run the following command in your terminal:

    enonic

It should output something that looks a bit like this:

.Main help page
----
Enonic CLI v.1.5.1
Manage XP instances, home folders and projects

USAGE:
   enonic [global options] command [command options] [arguments...]

COMMANDS:
     snapshot  Create and restore snapshots
     dump      Dump and load complete repositories
     export    Export data from a given repository, branch and content path.
     import    Import data from a named export.
     app       Install, stop and start applications
     repo      Tune and manage repositories
     cms       CMS commands
     system    System commands
     latest    Check for latest version
     vacuum    Removes old version history and segments from content storage
     help, h   Shows a list of commands or help for one command

PROJECT COMMANDS:
     sandbox  Manage XP development instances
     project  Manage XP development projects

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
----

If you want to know more about how to use one of the subcommands, you can use the `help` subcommand. For instance, if you want to know more about the `sandbox` subcommand, you can run

    enonic sandbox help

This should result in something like the following being printed to your screen:

.Sandbox help page
----
NAME:
   Enonic CLI sandbox - Manage XP development instances

USAGE:
   Enonic CLI sandbox [global options] command [command options] [arguments...]

VERSION:
   1.5.1

COMMANDS:
     list, ls         List all sandboxes
     start            Start the sandbox.
     stop             Stop the sandbox started in detached mode.
     create           Create a new sandbox.
     delete, del, rm  Delete a sandbox
     upgrade, up      Upgrades the distribution version.

GLOBAL OPTIONS:
   --help, -h  show help
----


== Sandboxes

When talking about _sandboxes_, we're actually talking about local instances of Enonic XP. Having a local (and running) instance of XP is essential for an effective development workflow.

Let's create a new sandbox by using the CLI. When you create a new sandbox, the CLI will present you with a few questions for configuring the sandbox, such as the sandbox name. To respond to a question, type in the desired response and press kbd:[enter].

[NOTE]
====
If you press kbd:[enter] without entering a response, the CLI will use the default response. The default response to a question is listed in parentheses after the question. For instance, the prompt for a sandbox name might look like this:

    ? Sandbox name (Sandbox1)

Here, `Sandbox1` is the default response.
====

Run the following command to get started:

    enonic sandbox create

When prompted, give your sandbox the name: `tutorial`. Next, when asked which XP distribution you want, use the latest one (at the top of the list).

The CLI will download the Enonic XP SDK distribution for your operating system and link it to the sandbox.

.Creating a sandbox
----
? Sandbox name: tutorial
? Enonic XP distribution: mac-sdk-7.2.0
Downloading distro [===================>--------------------------------]  37.64%
----

Once completed, we can use the CLI to start the sandbox:

    enonic sandbox start

Choose the `tutorial` sandbox and watch it boot up in your terminal. The boot output should look something like this, but with values adjusted for your system.

.Output when booting sandbox
----
                         _____
____________________________(_)______   ____  _________
_  _ \_  __ \  __ \_  __ \_  /_  ___/   __  |/_/__  __ \
/  __/  / / / /_/ /  / / /  / / /__     __>  < __  /_/ /
\___//_/ /_/\____//_/ /_//_/  \___/     /_/|_| _  .___/
                                               /_/

# Enonic XP 7.6.1
# Built on 2021-02-25T14:26:46Z (hash = 6359021fdb52fda156e39465d824153c915d903c, branch = 7.6)
# OpenJDK 64-Bit Server VM 11.0.10 (AdoptOpenJDK)
# Linux 5.4.108 (amd64)
# Install directory is $HOME/.enonic/distributions/enonic-xp-linux-sdk-7.6.1
# Home directory is $HOME/.enonic/sandboxes/tutorial/home
[...]
----


The initial output gives you a lot of information about this sandbox, including its home and install directories. We won't be needing them in this {document}, but knowing where you can find these details might be useful at a later time.

After the sandbox has started, you should see something like the following output in your terminal:

----
[...] - Started xp@523d2774{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[...] - Started api@22bce39c{HTTP/1.1,[http/1.1]}{0.0.0.0:4848}
[...] - Started status@37f8a3e8{HTTP/1.1,[http/1.1]}{0.0.0.0:2609}
[...] - Started @12314ms
[...] - Started Jetty
[...] - Listening on ports [8080](xp), [4848](management) and [2609](monitoring)
[...] - Searching for installed applications
[...] - Found [0] installed applications
[...] - Started Enonic XP in 11207 ms
----

This means that your local XP instance is up and running and ready to serve requests. The instance exposes the following ports:

* *8080*: Web
* *4848*: Management API (Used by the CLI when running commands against this XP instance)
* *2609*: Monitoring API (Used for metrics and instance info)

NOTE: To stop your sandbox, press kbd:[ctrl-c] in the terminal hosting the process. You can also run `enonic sandbox stop` in a different terminal instance.

=== Troubleshooting

If you have problems booting the sandbox, it may be that one or more of the ports used by XP are already in use. The command should warn you if something doesn't work right. It'll do this in one of two ways:

. If the CLI checks for the availability of some ports when starting up. If one of these ports isn't available, the CLI will abort with a message like this:

----
Port 8080 is not available, stop the app using it first!
----

. For ports where the CLI doesn't check for availability before starting, you might get an exception in the boot log. This is usually identifiable by a printed stack trace in your logs. Here's an example from what happens if port 4848 isn't available. The `[...]` replaces most of the stack trace for legibility reasons.

----
2021-04-06 11:24:01,168 ERROR c.e.xp.web.jetty.impl.JettyActivator - bundle com.enonic.xp.web.jetty:7.6.1 (80)[com.enonic.xp.web.jetty.impl.JettyActivator(171)] : The activate method has thrown an exception
org.apache.felix.log.LogException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:4848
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
[...]
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
	... 78 common frames omitted
----

If some ports are unavailable, you'll have to find out what programs are using those ports and then shut those programs down. How you find open ports varies from operating system to operating system, but if you're unsure about how to do it on your OS, check out the appropriate guide for https://www.cyberciti.biz/faq/unix-linux-check-if-port-is-in-use-command/[Linux], https://www.micahsmith.com/blog/2019/09/find-ports-in-use-on-macos/[macOS], or https://www.howtogeek.com/howto/28609/how-can-i-tell-what-is-listening-on-a-tcpip-port-in-windows/[Windows].

== Admin console

With your sandbox running, lets have a look at XP's admin console.
Point your browser to http://localhost:8080.

You should see the default XP login screen:

TODO: "login screen"


From the login screen, click "log in without a user". When working on a local development environment, we don't need to concern ourselves with users and administrators, so we'll get back to that in xref:chapter#_section[chapter X]. (TODO: do we? we should cover this at some point.)

After signing in, you will be greeted by the XP welcome tour. Complete the tour and install the applications listed in the final step. You'll need some of them later in this tutorial.

TODO: Screenshots of welcome tour

NOTE: If the welcome tour does not start automatically or if you want to take it again, you can always click the "XP Tour" icon on the home screen to start it manually.

== Projects and starters

With the sandbox up and running, we're ready to create our first XP project. Creating a project from scratch can be a daunting task for any system you're not familiar with, so to make things easier for you, Enonic provides a range of different project templates (known as _starters_). We'll make use of these throughout this tutorial.

NOTE: The complete list of starters can be found on https://market.enonic.com/starters[the Enonic Market].

For our first project, we'll use a minimal starter kit that provides only the essential files for an XP app. We'll use that to familiarize ourselves with how an XP app is structured and how to upload an app to XP. We'll look at producing content in later {document}s.

Here's how to use the CLI to create your first app. We'll use the "Vanilla starter" to create a project scaffold.

. Launch a new terminal
. When creating a project via the CLI, it creates a folder in your current working directory, so navigate to wherever you want your project to reside. Then, run this command:

    enonic project create

. Choose `Vanilla starter` from the list of available starters.
. Press kbd:[enter] to use the default name: `com.example.myproject`.
+
NOTE: Project names matter. XP does not support running two apps with the same name within a single instance.
+
. Use the default values for destination folder and version. If the destination folder already exists, you'll have to either choose another name for the folder or remove or rename the folder that already exists.
. When prompted to select a sandbox, choose the  `tutorial` sandbox we created earlier.
. Finally, press kbd:[enter] to skip opening the starter documentation. If you answer yes, the documentation for this starter will open in your browser. This is useful if you're using a starter you're not familiar with (and aren't following a guide).

If you used the default values as specified in the steps, a directory named `myproject/` should have been created during the process. If you used a different project name or project directory name, your directory will have a different name.

The project directory contains a bare bones XP application. The most relevant parts of the directory are:

.Essential XP project structure
[source,files]
----
build.gradle <--1-->
gradle.properties <--2-->
src/
  main/
    java/ <!--3-->
    resources/ <!--4-->
----

<1> The main build file for defining dependencies and more build-related details.
<2> Contains the standard project settings, as defined by the CLI.
<3> An optional folder for Java (XP apps may also contain Java).
<4> The main project folder. JavaScript code and assets are placed here.

== Building and deploying

With a brand new project setup, we are ready to build (compile) it for the first time, using the terminal once more:

. Change to the project directory:

    cd myproject

. Start the build with Enonic CLI:

    enonic project build

.Sample output from build process
----
Building in sandbox 'tutorial'...
Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 5s
3 actionable tasks: 3 executed
----


After building, a new file (and some folders) was created in your project structure: `build/libs/myproject.jar`. This is the actual application executable file.

To deploy the app to the sandbox, use the CLI once again:

. From the project folder:

    enonic project deploy

The application file will now be copied your sandbox' home/deploy/ folder. XP then detects and starts the app.

Confirm that your application was started by looking at the log file from the sandbox' terminal window:

.Application output
----
[...] - Local application [com.example.myproject] installed successfully
[...] - Application [com.example.myproject] started successfully
----

NOTE: Running `enonic project deploy` will also build your project if needed. It will even start the sandbox if it is not running already.

You can also verify that the application was installed by using the admin console. Open the "Applications" app from the main launcher panel to find the application in the list.

TODO Screenshot:

Congratulations on building your first Enonic application :-)


== Summary

=== Useful links

=== Next
