= Content and content types
:toc: right
:imagesdir: media

In this chapter, we'll use the headless starter to create our first
GraphQL API.

Because the 'headless starter' is completely bare(?), we'll have to do
things from the ground up.

== Create a headless API project

This section walks the user through creating a new project using the
headless starter. We've already created a project previously, so it
needn't be _as_ detailed as previously, but should still provide all the
necessary instructions.

== Setting up Content Studio

Next, we'll log into the admin UI and install Content Studio and create
a site.

NOTE: Projects are a new feature in Content Studio, introduced in 7.3.0. They
are not essential and for a small demo like this would probably cause
more issues than they solve. However, it's probably worth sticking a
note in here, telling the users that there is a more advanced concept
called projects which is useful for working with multiple
sites/contexts. We might explore this later.

After creating the site, we'll see that there are no content types! The
only things we can create are folders, shortcuts, sites, and template
folders. We'll change that in the next section.

== My first content type

This section gives a brief explanation of XP content types: what they
are and how to create them. By doing this, it also introduces the
directory structure of an XP app.

We'll keep it light for now and only introduce what we need.

After creating the content type, we'll open Content Studio and check it
out + create an instance of the content type.

== Querying the API

Now that we've created some content, how about we try and query the API
to see if we can fetch it?

Introduces the GraphQL API (and mentions that it's automatically
generated by Guillotine) and how to use it.
