= {title-deployment}
include::.variables.adoc[]
:description: {description-deployment}

Working on your local copy is great for development, but you can't expose what you build to someone else that way. For that, you need to deploy XP and your app to somewhere. In this {document}, we'll give a high-level overview of how you do just that.

== Deployment

You have two main choices for deploying XP:

* Run it _as a service_ on the Enonic Cloud
* Self-host it

Enonic recommends using Enonic Cloud for a smoother experience, but you can choose to self-host it yourself if that better suits your requirements.

=== Enonic Cloud

Enonic offers a fully managed way to run XP, known as the Enonic Cloud. As a user of Enonic Cloud, you can sit back and relax and let Enonic take care of all your infrastructure, including monitoring, backups, automation, and more.

This is by far the easiest way to get an XP installation up and running. To learn more about it and get a free trial, head over to https://enonic.com/platform/platform-as-a-service[the Platform as a Service page].

=== Self-hosted

If relying on cloud services isn't for you, you can also self-host the Enonic platform. There's a number of different deployment strategies to choose from, based on what suits your particular situation the best.

To learn more about self-hosting and deployment strategies, check out https://developer.enonic.com/docs/xp/stable/deployment[the _deployment_ section of the XP reference docs].

== Virtual hosts: managing paths

Virtual hosts (vhosts) let you safely expose services (such as sites and web apps) through public domains. XP provides the following endpoints by default:

`localhost:8080/webapp/<app-name>/`:: Web app engine
`localhost:8080/site/<repo>/<branch>/<path>`:: Site engine
`localhost:8080/admin/`:: Admin engine

Vhosts allow you to route traffic to domains and URL patterns to service paths of your choosing.

For instance, if you own the `example.com` domain and use XP to serve the content at that URL, you could create a mapping so that any traffic to `example.com` is re-routed to XP's `:8080/site/default/master/homepage`, assuming that's where you keep the content you want to serve.

To configure vhosts, create a vhost configuration file and place it in `XP_HOME/config/com.enonic.xp.web.vhost.cfg`, where `XP_HOME` is your XP distribution's installation folder (read more about that in the https://developer.enonic.com/docs/xp/stable/deployment/distro[distributions chapter]).

This example vhost config would set up the mapping listed above plus an additional mapping of `example.com/admin` to `:8080/admin`:

[src,properties]
----
enabled = true <--.-->

mapping.example.host = example.com
mapping.example.source = / <--.-->
mapping.example.target = /site/default/master/homepage

mapping.adm.host = example.com
mapping.adm.source = /admin <--.-->
mapping.adm.target = /admin
mapping.adm.idProvider.system = default
----

<.> Enable vhosts configuration
<.> Map  everything from `/` (the base path) to the following target
<.> Map `/admin`  to `/admin` and add an ID provider.

Using the above mapping, requests to `example.com/some/path` would be redirected to `8080/site/default/master/homepage/some/path` and `example.com/admin` `8080/admin`.

Visit the https://developer.enonic.com/docs/xp/stable/deployment/vhosts[vhosts reference documentation] for a more thorough explanation of how they work and further reading.

== What's next?

Congrats! You've reached the end of the introduction for now. This document is still a work in progress and new content will be added at a later date. If you'd like to go further now, why don't you try one of the following guides which introduce extra aspects of the XP experience?

https://developer.enonic.com/guides/headless-cms-intro[Introduction to headless CMS]:: If you've enjoyed the headless aspects of this introduction, why not visit this guide to further your knowledge of how to use the GraphQL API and how to customize it.
https://developer.enonic.com/guides/my-first-site[My first site]:: If you're interested in building a traditional CMS-based application with server rendered pages, this is the guide for you. It covers building pages and using more Content Studio building blocks such as regions, parts, and page templates.
https://developer.enonic.com/guides/my-first-webapp[My first webapp]:: If you're more interested in building web apps than web sites, how about this guide which focuses more on the web app aspects, including JavaScript controllers, serving assets, and routing.
