= Headless API
include::variables.adoc[]

In the {document}s leading up to this, we've seen a number of GraphQL queries. We've also mentioned that it's an application called _Guillotine_ that's responsible for generating the GraphQL API. However, we haven't yet looked at how the API is integrated into an application. That's what this {document} is for, along with a slightly more advanced search technique using something called _queries_.

NOTE: This section should reference the https://developer.enonic.com/guides/headless-cms-intro[headless CMS intro guide]  somehow, but I'm not sure how best to do that yet.

== The Guillotine library

If you've been wondering how the GraphQL API we've been querying up until now was created: the Guillotine library is the answer. The Guillotine library analyzes all the content in your applications and generates an API from that. It' s an optional library that comes preconfigured with the headless starter that we used back xref:apps#_projects_and_starters[way back when we first created our app in a previous {document}]. Guillotine provides direct, typed, and documented access to content within your site.

If you're familiar with GraphQL, you might have noticed that we have not performed any mutations yet. The reason for that is simple: Guillotine only exposes the read-only part of the Enonic Content API, so mutations are not available.

=== Integrating Guillotine

When

To use guillotine in an app,

[source,groovy]
----
plugins {
    id 'com.enonic.xp.app' version '3.0.0'
}

apply plugin: "com.enonic.xp.app"

app {
    name = "${appName}"
    displayName = "${appDisplayName}"
    vendorName = "${vendorName}"
    vendorUrl = "${vendorUrl}"
    systemVersion = "${xpVersion}"
}

dependencies {
    compile "com.enonic.xp:portal-api:${xpVersion}"
    include "com.enonic.xp:lib-websocket:${xpVersion}"
    include "com.enonic.lib:lib-guillotine:5.0.1"
    include "com.enonic.lib:lib-graphql-playground:0.0.1"
}

repositories {
    mavenLocal()
    jcenter()
    xp.enonicRepo( 'dev' )
}
----

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<site>
  <form />
  <mappings>
    <mapping controller="/controllers/graphql.js" order="50">
      <pattern>/api</pattern>
    </mapping>
  </mappings>
</site>
----

== Advanced querying: using the _search_ function

== How does it work in XP?

In XP, `lib-guillotine` creates the API for us ...

To check it out, you can head to {p1-api-url}.

== Still want to learn more?

The https://graphql.org/learn/[_Introduction to GraphQL_ documentation] is a good place to start! It walks you through

https://developer.enonic.com/docs/guillotine/stable[the Guillotine reference docs] are also a great place to go for some more info.
