

* Getting started outline

1. Setting up your dev environment
   In which we walk through getting set up for development.

2. Development basics
   In which we introduce basic Enonic tools and concepts, including
   the CLI, sandboxes, and projects.

3. Creating a content type
   In which we introduce the concept of content types and explain how
   to create them. We'll end the chapter by having the user fetch some
   content that they've created, showcasing the guillotine package.

4. An input type deep dive
   In which we take the content concepts from the previous chapter and
   expand on them. Show the reader how they can create more complex
   content types.
   1) The most important input types
      This section focuses on the key input types available to the
      user. They'll use these all the time. Add some extra focus to
      the text area input type.
   2) Additional input types
      A section briefly covering the less commonly used input types.
      Should link to reference docs for input types.
   3) Input type configuration
      Including controlling occurrences and other ways you can
      configure the inputs. We've looked at a number of inputs now and
      have seen some attributes and configuration options. Let's
      explore them further.
   4) Mixins
      Show how we can use mixins to reuse input fields across content types.

5. Advanced content types
   1. Item sets
   2. Option sets

6. Headless API
   A GraphQL introduction, reference hmdb guide.
   1. queries
   2. relations

7. Controllers: controlling your application
   In which we move onto more a more advanced topic: controllers and
   error handling
   1. Application controllers
   2. HTTP controllers
   3. Error handling
   4. Mappings: use ~lib-guillotine~ as an example to explain this.

8. Assets
   Link to lib-static

9. Content API
   Focus on the read portion

10. Filters and routing
    In which we look at filters and application routing.
    Link to my first webapp

11. Sites and pages -- the 'headful' side of XP
    In which we introduce the more traditional side of XP. This should
    be an optional chapter for users that want to know about using XP
    as a traditional CMS. If possible, structure this chapter so that
    the user can skip it without missing out on anything important for
    their use case.

12. Enonic Market
    A short, optional chapter in which we introduce the Enonic Market.

13. Auth
    In which we look at setting up Auth for your XP application using
    the Enonic Market. Use the 'Simple ID Provider' package and provide
    links for the other relevant packages.

14. Storing data
    Writing data
    Now that the end user can sign in, let's handle storing data that
    they provide.

15. Admin extensions

16. Deployment
    1. virtual hosts

17. Next steps
