= Setting up the development environment
:toc: right
:imagesdir: media
:experimental:
:document: chapter

Before we can start building apps and APIs, let's make sure we have the right tools available to work efficiently with XP. This {document} walks you through installing the fundamental tools we will be using throughout this guide, including a text editor, a package manager for your system, Git, and the Enonic CLI. If you've already got these installed, feel free to skip to the next chapter (or to the relevant sections if you're missing some of them).

== Introducing the command line

The command line -- aka _the terminal_-- is a powerful, text-based interface for running commands on your computer. You can also use use the terminal to navigate your file system, similar to macOS`' Finder or Windows`' Explorer. The program running in the terminal (that interprets your commands) is known as a _shell_.

The rest of this {document} will focus primarily on working with the command line, so go ahead and open your favorite terminal. If you don't know how to open a terminal on your system, don't worry! Instead, check out the guide for https://www.macworld.co.uk/how-to/mac-software/how-use-terminal-on-mac-3608274/[macOS], https://www.lifewire.com/how-to-open-command-prompt-2618089[Windows], or https://www.howtogeek.com/140679/beginner-geek-how-to-start-using-the-linux-terminal/[Linux] (depending on your operating system).

When we ask you to "run a command" later on in this document, you can assume that we're asking you to run it in a terminal unless otherwise specified.

NOTE: To run a command in your terminal, type in the command and press kbd:[enter]. For instance, the command `cd myfolder` would change the shell's working directory to the `myfolder` directory, assuming that it exists.

== Package managers
Enonic provides a command line interface (CLI) for working with XP. To make it easy to install and keep it updated, we distribute it via a number of _package managers_. Package managers are terminal-based "app stores" that focus on developer and command line tools.

Find the section below for your operating system to see what package managers we support and how to install them.

=== macOS: Homebrew

For macOS, we distribute the Enonic CLI through the popular package manager https://brew.sh/[Homebrew]. Homebrew lets you install, uninstall, and manage your command line tools, including updating them when new versions are made available.

To install Homebrew, follow the instructions in the link above or run the following command:

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Once installed, run the following command in your terminal to verify that everything is working:

    brew help

=== Windows: Scoop

We use the https://scoop.sh/[Scoop] package manager for Windows. To install Scoop, visit their website, or simply run these two commands from Powershell:

NOTE: To launch Powershell from your regular terminal, the _Command Prompt_, simply execute the command `powershell`. The prompt should then start with `PS`.


    set-executionpolicy remotesigned -scope currentuser
    iwr -useb get.scoop.sh | iex

To verify that Scoop was installed successfully, run the following command:

    scoop help

=== Linux: Snapcraft

We use Snapcraft to distribute packages for Linux. Snapcraft comes preinstalled on a number of popular Linux distributions, including Ubuntu and Manjaro, and is also available for most other major Linux distributions, such as Debian, elementary OS, and Pop!_OS.

Specific instructions will vary according to your distribution, so be sure to consult the https://snapcraft.io/docs/installing-snapd[snapd installation instructions] for your particular distro.

To verify that it's installed and available, run the following command in your terminal. It should print out your version of Snap.

    snap version

== Installing the Enonic CLI

Now, we'll install the Enonic CLI via the package manager we just set up. The CLI provides a number of enonic-specific commands designed to make working with XP fast, easy, and efficient.

[NOTE]
====
While we heavily recommend using a package manager, you can also download and install the executables manually if you prefer. To do that, find your desired version and operating system https://repo.enonic.com/public/com/enonic/cli/enonic/[here], download the files you need, and install them as you would any other binary files on your system.
====

Follow the instructions for your specific operating system below. When you have installed the CLI, verify that it's working by running

  enonic version

=== macOS

From your terminal, run the following commands:

    brew tap enonic/cli
    brew install enonic

To upgrade to newer versions of enonic CLI when they become available, run the command `brew upgrade enonic`

=== Windows

From a Powershell terminal, run the following commands:

    scoop bucket add enonic https://github.com/enonic/cli-scoop
    scoop install enonic

To upgrade to newer versions of enonic CLI when they become available, run the command `scoop update enonic`

=== Linux

From your terminal, run the following command:

   sudo snap install enonic

Snap automatically keeps your snaps updated. To manually force an update, run the command `sudo snap refresh enonic`


== Git

Git is a free and open source _distributed version control system_. Later on in this tutorial, we will create new Enonic development projects using _starters_. The Enonic CLI uses Git to download these starters and to prepare the files for your project locally.

To install Git, follow the notes for your operating system below.

Once you have installed Git, you can verify that it's working correctly by running the following command:

    git version


=== macOS

NOTE: Apple maintains its own fork of Git. If you have XCode installed, you already have Git installed too.

To install Git via Homebrew, run this command:

    brew install git

=== Windows

To install Git using Scoop, run the following command from Powershell:

    scoop install git

=== Linux

To install Git with Snapcraft, run the following command:

   sudo snap install git


== Set up a text editor

Text editors (or _editors_ for short) are applications
designed specifically for writing computer code. There are a range of available editors out there. If you do not already have a good editor, follow the steps below to get one:

=== Download VS code

Visit the https://code.visualstudio.com/Download[VS Code download page] to download and install the version matching your operating system.

=== Install Prettier plugin

Addint the _Prettier - Code formatter" plugin to VS code helps format your code and avoid common typing mistakes.

Follow these steps to install the VS Code plugin:

. Open the VS Code extensions panel (View => Extensions).
. Search for: “Prettier - Code formatter”.
. Click “Install”.

NOTE: When the installation is finished, you must restart VS Code to activate the Prettier.


== Summary

You have now installed a package manager for your OS, Enonic CLI, Git and a Code editor. You will be using these tools throughout the various steps of this tutorial.

=== Useful links

* Visit the Enonic CLI documentation for a full overview
* Learn more about Git from this useful https://guides.github.com/introduction/git-handbook/[handbook by Github].


=== Next

In the next step, you
